### ISSUE TITLE
The github 'timeline' dataset is deprecated

### ISSUE THREAD

**Issue by andrea-soto** [EvanKepner/bazaar#12]
For 2015 data we need to use the year/month/day tables. 

Last events recorded in the 'timeline' table are from December/2014. Why? Change in API.

From [https://www.githubarchive.org/](https://www.githubarchive.org/)
- Activity archives for dates between 2/12/2011-12/31/2014 was recorded from the (now deprecated) Timeline API.
- Activity archives for dates starting 1/1/2015 is recorded from the Events API.

**Comment by EvanKepner** [comment]
That might also explain the issue I had with repository_language in the sample I took from 01/01/2015. We do have a created_at field, so we could use map-reduce to group by year-month-repo and total events.
