### ISSUE TITLE
Decide what data we want to use

### ISSUE THREAD

**Issue by andrea-soto** [EvanKepner/bazaar#13]
If recent (2015) - daily or monthly? Daily data is ~2.5 GB each and monthly data ranges from 30 GB to 50 GB

If 2014 and older - we can use the timeline dataset

**Comment by EvanKepner** [comment]
How do we feel starting with 2015 since that's most recent? I was able to download a .json.gz file from the archive from 2015-12-31 that had 27k events.

**Comment by EvanKepner** [comment]
sorry, accidentally clicked closed when I thought it was cancel
