### ISSUE TITLE
Pick Top 5-10 OSS Projects for a Sample

### ISSUE THREAD

**Issue by EvanKepner** [EvanKepner/bazaar#16]

**Comment by EvanKepner** [comment]
Big Python projects: 

1. https://github.com/pydata/pandas
2. https://github.com/numpy/numpy
3. https://github.com/scikit-learn/scikit-learn
4. https://github.com/django/django
5. https://github.com/matplotlib/matplotlib

Small-Mid Python projects: 

1. https://github.com/sloria/TextBlob
2. https://github.com/Yelp/mrjob
3. https://github.com/nltk/nltk
4. https://github.com/Kinto/kinto
5. https://github.com/graphql-python/graphene/

**Comment by EvanKepner** [comment]
Lots of featured repos listed in the archives here: http://pycoders.com/archive/

**Comment by andrea-soto** [comment]
Downloaded a sample of python repos with 35+ stars
