### ISSUE TITLE
Establish benchmarks based on analysis for health

### ISSUE THREAD

**Issue by EvanKepner** [EvanKepner/bazaar#24]

**Comment by dails08** [comment]
I'll start looking into issue closer patterns, i.e, how long it takes issues to get closed, how often they're reopened, how many people are closing issues, etc.

**Comment by EvanKepner** [comment]
Adding what I've found related to unique actors: 

Potential metric: ratio of avg. open to avg. close unique actor times min. unique actors for the repo. A score <= 1 would be good, since that means on average the same density of unique users work to identify issues and close issues, or there are plenty of people who help resolve issues when they are identified. A higher score could mean that the min UA is high, implying that users are not able to identify and resolve bugs independently. It could also mean that many more people are identifying bugs (avg. open UA) than working to close them (avg. close UA).

**Comment by EvanKepner** [comment]
Adding distribution of custom UA metric: 

![dist_ua_metric](https://cloud.githubusercontent.com/assets/8532682/13108543/b4aaa854-d541-11e5-93ac-7127cedc8e42.png)
