### ISSUE TITLE
Re-fromat dates so that type is Data instead of String

### ISSUE THREAD

**Issue by andrea-soto** [EvanKepner/bazaar#40]
Mongo's aggregate has a couple of useful date operations that work with date types. 

I've re-formatted the "created_at" date in a subset of the data I created for testing, but it could be useful to do this for the whole dataset to make date calculations in the future easier to do.

**Comment by EvanKepner** [comment]
I've created a copy of "PythonIssues" called "PyIssueDate" that has the date conversion from your script applied in the prod db. Awesome idea!
