### ISSUE TITLE
How can we identify projects by code e.g. select only python projects?

### ISSUE THREAD

**Issue by EvanKepner** [EvanKepner/bazaar#8]

**Comment by andrea-soto** [comment]
The 'repository_language' specifies the programming language(s) of the repo

**Comment by EvanKepner** [comment]
Nice - when I was looking through the json I downloaded in the sample I didn't that field. There might be some additional magic in google, or the sample is incomplete. The code I tested was `db.getCollection('jan').find({'repository_language':{$exists:true}})`

**Comment by andrea-soto** [comment]
It seems like  repository_language is part of the old schema but not the new. The new schema has a 'payload' which depends on the type of event. I'm trying to see if there is an event (like create) that has the language. I'll let you know if I find it.

**Comment by andrea-soto** [comment]
I found the language for the new schema.
The data  has 	a "repo_url" field which links to a JSON file containing information about the repo, and in that JSON data there is a subfield called "language".

For example, this is the repo_url for one project: [https://api.github.com/repos/bitbinio/bitbin](https://api.github.com/repos/bitbinio/bitbin). For this repo, the language is JavaScript

**Comment by EvanKepner** [comment]
Cool, for the raw json files this ties into the other issue I posted on acquisition: 

https://github.com/EvanKepner/bazaar/issues/7
