### ISSUE TITLE
Map-Reduce to aggregate commits over time by repo

### ISSUE THREAD

**Issue by EvanKepner** [EvanKepner/bazaar#9]

**Comment by dails08** [comment]
This can be one of the first things I do once I warehouse the data

**Comment by EvanKepner** [comment]
I started to test mapreduce code as well, first pass is here (JavaScript). You can run it against the test server with `mongo localhost:27017/test scriptFileName.js`

https://github.com/EvanKepner/bazaar/blob/7a94c2c0cc35c1ccf327b9c360f20ddda6743f7c/test_map_reduce/map_reduce_issueTypes.js

**Comment by EvanKepner** [comment]
From the new script I made we might be able to adjust this. I'm looking at raw types, but there is also actions in the payload field, as well as state under payload.issues.
